# Generated by Django 5.0.14 on 2026-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('VENDEDOR', 'Vendedor'), ('DISPOSITIVO', 'Dispositivo')], default='VENDEDOR', max_length=15),
        ),
    ]
