# Generated by Django 5.0.14 on 2026-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN de 4 dígitos (obrigatório para vendedores)', max_length=4, null=True, verbose_name='PIN do Vendedor'),
        ),
    ]
