# Generated by Django 5.0.14 on 2026-08-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
        ('users', '0003_customuser_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='gestao.cliente'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ADMIN_CLIENTE', 'Administrador do Cliente'), ('SUPERVISOR', 'Supervisor'), ('VENDEDOR', 'Vendedor'), ('DISPOSITIVO', 'Dispositivo')], default='VENDEDOR', max_length=15),
        ),
    ]
