# Generated by Django 5.0.14 on 2026-04-25 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='core.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='core.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('venda_fechada', models.BooleanField(default=False)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='core.metrica')),
            ],
            options={
                'verbose_name': 'Relatório de Atendimento',
                'verbose_name_plural': 'Relatórios de Atendimentos',
            },
        ),
    ]
