# Generated by Django 5.0.14 on 2026-05-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
