# Generated by Django 5.0.14 on 2026-08-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_equipe_ativo_loja_ativo_metrica_ativo'),
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='gestao.cliente'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='gestao.cliente'),
        ),
    ]
